[build]
  command = "npm run build && npm run export"
  publish = "out"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"

[[redirects]]
  from = "/all-posts/"
  to = "/blog/"

[[redirects]]
  from="/pocket-articles"
  to="/reading-list/pocket-articles"

[[redirects]]
  from="/raindrop-links"
  to="/reading-list/raindrop-links"

[[redirects]]
  from="/feedbin-stars"
  to="/reading-list/feedbin-stars"