[build]
  command = "npm run build && npm run export"
  publish = "out"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    Content-Security-Policy = "default-src 'none'; connect-src 'self' https://vitals.vercel-insights.com; img-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self'"